# -*- coding: utf-8 -*-
"""assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/sk-classroom/starter/blob/main/assignment/assignment.ipynb

<a target="_blank"
  href="https://colab.research.google.com/github/sk-classroom/starter/blob/main/assignment/assignment.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

![](https://www.bleepstatic.com/content/hl-images/2022/04/08/GitHub__headpic.jpg)

# About this assignment

In this assignment, we will learn how to submit the assignment to the GitHub Classroom.

## How the grading works

When you submit your code, GitHub Actions automatically runs predefined tests on your submission. These tests check if your functions work correctly by comparing their outputs with expected results.

The test process is as follows:

1. Push your code to GitHub
2. Tests run automatically
3. Get immediate feedback via green ✓ or red ✗ marks
4. View detailed test results in Actions tab

## Tips
- Run tests locally before submitting
- Check error messages carefully
- Commit and push after each major change


## Protected files

Protected files are test files and configuration files you cannot modify. They appear in your repository but don't make any changes to them. You can change them and commit them to your repository, but any changes you make to them will be notified to the instructor for review.

## Integrity

There is a system that automatically checks code similarity across all submissions and online repositories. Sharing code or submitting copied work will result in zero credit and disciplinary action. While you can discuss concepts, each student must write their own code. Cite any external resources, including AI tools, in your comments. Start early and ask for help during office hours if needed. The goal is to learn through genuine effort, not shortcuts.

# Assignment

Complete the following tasks and upload your notebook to your GitHub repository.

1. Fill in the blank functions, marked by, "\#TODO", in the notebook
2. Update this notebook by using `git add`, `git commit`, and then `git push`.
3. The notebook will be automatically graded, and your score will be shown on GitHub. See [how to check the results on GitHub](https://docs.github.com/en/education/manage-coursework-with-github-classroom/learn-with-github-classroom/view-autograding-results)

Dont's:
- Do not import any libraries except for the ones that are already imported. The grading script will not work if you import additional libraries.
- Do not change the name of the functions. The grading script will not work if you change the name of the functions.
- DO not remove the cells with tag "gradable". If you happen to remove the cells with tag "gradable", recreate the cell and add the tag "gradable" to the cell.

Do's:
- Make the code clearn and easy to understand. Consider using linters & formatters such as `black`. [Youtube: Linters and fixers: never worry about code formatting again (Vim + Ale + Flake8 & Black for Python) by Yong-Yeol Ahn](https://www.youtube.com/watch?v=4FKPySR6HLk)
- You can add additional cells as you like. If you want to include the additional cells in the grading, you need to add the tag "gradable" to the cell. Otherwise, your additional cells will be stripped out when grading.

## Libraries

In the assignment, you can only use the specified libraries. You cannot import any other libraries that result in the grading script failing or a zero score. So make sure NOT to import any other libraries! For example,
"""

import numpy as np
from sklearn.decomposition import PCA

"""This means that you can use numpy and PCA from sklearn.decomposition, but you cannot use any other libraries, including the other functions from sklearn.

## Task 1

Let us learn how the grading works through the following example. There is two types of cells in this notebook:

1. cells with tag "gradable," and
2. cells without the tag "gradable".

Only the gradable cells will be used for grading, meaning that any changes you make to the cell without the tag "gradable" will be stripped out when grading.

For example, the following cell is not a gradable cell.
"""

# All cells without the tag "gradable" will be stripped out when grading.
a = 1
b = 1

"""The following cell is a gradable cell. Typically, the gradable cells are functions that you need to implement."""

# TODO
def count_characters(s):
    """
    Count the number of characters in the string.

    Args:
        s: a string
    Returns:
        an integer representing the number of characters in the string
    """
    return len(s)

"""### Submitting Your Work

After completing your work, you can upload your notebook either through GitHub's website interface or using command line git commands. For this assignment, let's use the website method.

1. Go to your repository on the GitHub website
2. Click "Add file" button on the top right corner
3. Click "Upload files"
4. Select the notebook file you want to upload
5. Click "Commit changes"

### Viewing Test Results

The results of the tests will be posted on the "Actions" tab on GitHub. Let's check the results.

1. Go to your repository on the GitHub website
2. Click "Actions" tab on the top
3. Click "autograding" workflow
4. Click "Test results"

### Test Times

Don't worry if tests take 1-2 minutes to complete. This happens because GitHub Actions creates a fresh virtual environment for each submission, installing Python and required packages. While tests run, you'll see a yellow dot that changes to either a green checkmark or red X when complete. This clean-environment approach ensures fair and consistent testing of your code.

If you want to check the code right away, you can check out the test code "test_xx.py" under ./tests folder. And copy and paste the code to your notebook to the cell following the cell that contains the function you want to test.

The test looks something like this.
"""

count = count_characters("Hello")
assert count == 5, "The function should return 5"

"""Now, complete the following tasks.

## Task 2

Create a function that takes a sentence and returns a list of lowercase tokenized words. Each token is a subtring separated by spaces.
"""

# TODO: Implement the function
def tokenize_sentence(sentence):
    """
    Tokenize the sentence into lowercase words.

    Args:
        sentence: a string
    Returns:
        a list of lowercase words
    """
    pass  # Implement the function

"""## Task 3

Implement a function to remove common English stopwords.
"""

# TODO: Implement the function
def remove_stopwords(tokens, stopwords):
    """
    Remove common English stopwords from the list of tokens.

    Args:
        tokens: a list of lowercase words
    Returns:
        a list of lowercase words without stopwords
    """
    pass  # Implement the function

"""# Task 4

Calculate word frequency in a given text and return a list of tuples with word and frequency.
"""

# TODO: Implement the function
def calculate_word_frequency(tokens):
    """
    Calculate word frequency in a given text.

    Args:
        tokens: a list of lowercase words
    Returns:
        a list of tuples with word and frequency
    """
    pass  # Implement the function